name: do_dart
description: A new Flutter package project.
version: 0.0.1
author: Davenson Lombard <me@dlombard.net>
homepage: https://github.com/dlombard/do_dart

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  json_annotation: ^2.0.0
  http: ^0.12.0+1
  dio: ^2.0.0
  dotenv: ^1.0.0

dev_dependencies:
  build_runner: ^1.0.0
  json_serializable: ^2.0.0
  test: ^1.5.3

