name: do_dart
description: do_dart is an implementation of the digitalocean api which can be used on mobile, web or server
version: 0.1.7
homepage: https://github.com/dlombard/digitalocean_dart

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  json_annotation: ^3.0.0
  dotenv: ^2.0.0

dev_dependencies:
  build_runner: ^1.0.0
  json_serializable: ^3.0.0
  test: ^1.5.3

