name: do_dart
description: do_dart is an implementation of the digitalocean api which can be used on mobile, web or server
version: 0.1.3
author: Davenson Lombard <me@dlombard.net>
homepage: https://github.com/dlombard/digitalocean_dart

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  json_annotation: ^2.0.0
  dio: ^2.0.0
  dotenv: ^1.0.0

dev_dependencies:
  build_runner: ^1.0.0
  json_serializable: ^2.0.0
  test: ^1.5.3

