name: do_dart
description: do_dart is an implementation of the digitalocean api which can be used on mobile, web or server
version: 2.0.0-dev.0
homepage: https://github.com/dlombard/digitalocean_dart

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  json_annotation: ^4.0.0-nullsafety.0

dev_dependencies:
  build_runner: ^1.12.2
  json_serializable: ^4.1.0-nullsafety.0
  test: ^1.16.8
  random_string: 2.2.0-nullsafety

